### PR TITLE
Provide ubuntu-seed mount

### PR DESCRIPTION
**Pull request by xnox**

### CODE REVIEW

**Comment by xnox** [comment]
I'm not sure, but I think this is what we need to do upon initialization.... at least for the recover mode.

**Comment by mvo5** [comment]
Yes, this works,let's do it!

**Comment by mvo5** [comment]
Will you do this differently or why is it closed? Or should I reopen the code that does it in snap-bootstrap initramfs-mounts ?

**Comment by mvo5** [comment]
Should https://github.com/snapcore/snapd/pull/7797 be reopened?

**Comment by xnox** [comment]
Merged as a rebase....

**Pull request closed without merging**
