### PR TITLE
Allow to update password policy

### PR DESCRIPTION
**Pull request by snowsky**
Thanks for helping us make a better ubuntu core!

Before continuing with the PR, you might want to consider also creating a PR for the new core-base repository
at https://github.com/snapcore/core-base, which contains newer core versions (22+), if the PR is also relevant
for newer core versions.

(Will put up a PR for uc22+ after this is merged)

### CODE REVIEW

**Comment by snowsky** [comment]
Thanks for the hint. It is a good point to use plugin. I'd like to update the password policy as in here, https://helpful.knobs-dials.com/index.php/PAM_notes.

**Comment by snowsky** [comment]
`pam_cracklib` may be a good candidate for the new plugin, https://www.thegeekdiary.com/pam-password-complexity-and-pam_cracklib-credit-system-in-centos-rhel/.

**Comment by vorlonofportland** [comment]
> `pam_cracklib` may be a good candidate for the new plugin, https://www.thegeekdiary.com/pam-password-complexity-and-pam_cracklib-credit-system-in-centos-rhel/.

pam_cracklib is obsolete, so no.  It is superseded by either pam_pwquality or pam_passwdqc.

**Comment by valentindavid** [comment]
I suggest we add pam_pwquality since this is what Ubuntu classic has by default. And then we make `/etc/security/pwquality.conf` writable. @snowsky if you want to make such a pull request you are welcome.

**Comment by snowsky** [comment]
Cool, do we need to install a package for pam_pwquality or pam_passwdqc? I saw `pam_passwdqc` in `core-initrd` but not sure if a package has to be installed first.

**Comment by valentindavid** [comment]
Yes, we should add `libpam-pwquality` package. Add it `001-extra-packages.chroot`. Probably call `pam-auth-update --enable pwquality` or something like that in new a hook script. Add `/etc/security/pwquality.conf` in `static/etc/system-image/writable-paths`.

**Comment by snowsky** [comment]
Thanks @valentindavid for the details. Just pushed a new commit. qq? Is there anything we need to be careful about the sequence of hooks so the new hook will not overwrite the existing `password` settings from extrauser plugin. Thanks 👍

**Comment by mvo5** [comment]
Hey @snowsky - thanks so much for this PR! Could you please sign our CLA at https://ubuntu.com/legal/contributors ? Then we can merge your PR :)

**Comment by snowsky** [comment]
Hi @mvo5 I just submitted the form :)

**Comment by snowsky** [comment]
Just to touch base, before merging the PR, any tests we should conduct? Thanks 👍

**Comment by snowsky** [comment]
Hi @valentindavid and @vorlonofportland, just to touch base, before merging the PR, any tests we should conduct? Thanks 👍

**Comment by valentindavid** [comment]
Sorry, for the delay. I have tested it and it works well.
Before we merge, could you squash your commits into one? And could you open the same PR to core-base?

**Comment by snowsky** [comment]
Thanks @valentindavid for the update. No worries at all. Please approve 2 PRs. :) Also curious of how you tested. Did you side-load a testing core20 snap?

**Comment by valentindavid** [comment]
This is what I did to manually test.
I built a new image with a build of core20 from your branch. Then spawned a new VM with that image. Logged in. Created a test user. Logged as it. Tried to change password. Changed the pwquality configuration. Tried again to see if it had any effect.

**Review by valentindavid — APPROVED** [review]

**Comment by Meulengracht** [comment]
LGTM, I merged this  @valentindavid, hope you don't mind

**Pull request merged**
