### PR TITLE
Switch to self-hosted runners for Github Actions

### PR DESCRIPTION
**Pull request by Meulengracht**
Should fix our PRs for forks.

### CODE REVIEW

**Review by sergiocazzolato — APPROVED** [review]
Nice

**Review by alfonsosanchezbeato — APPROVED** [review]
\o/ thanks!

**Comment by xnox** [comment]
Nice! is there anything else that needs to happen to make the self hosted things work?

**Comment by Meulengracht** [comment]
> Nice! is there anything else that needs to happen to make the self hosted things work?

Nothing, sergio has already done all the hard work!

**Pull request merged**
