### PR TITLE
hooks: use ppa:ucdev/base-ppa/ubuntu instead of ppa:canonical-foundations/ubuntu-image

### PR DESCRIPTION
**Pull request by mvo5**
Let's pull things from the same PPA as core-base

### CODE REVIEW

**Comment by Meulengracht** [comment]
The spread test fails with the following

``` 
Reading package lists...
W: https://ppa.launchpadcontent.net/ucdev/base-ppa/ubuntu/dists/focal/InRelease: No system certificates available. Try installing ca-certificates.
W: https://ppa.launchpadcontent.net/ucdev/base-ppa/ubuntu/dists/focal/Release: No system certificates available. Try installing ca-certificates.
E: The repository 'https://ppa.launchpadcontent.net/ucdev/base-ppa/ubuntu focal Release' does not have a Release file.
```

**Comment by mvo5** [comment]
> The spread test fails with the following
> 
> ```
> Reading package lists...
> W: https://ppa.launchpadcontent.net/ucdev/base-ppa/ubuntu/dists/focal/InRelease: No system certificates available. Try installing ca-certificates.
> W: https://ppa.launchpadcontent.net/ucdev/base-ppa/ubuntu/dists/focal/Release: No system certificates available. Try installing ca-certificates.
> E: The repository 'https://ppa.launchpadcontent.net/ucdev/base-ppa/ubuntu focal Release' does not have a Release file.
> ```

Thanks, fixed (hopefully)

**Review by alfonsosanchezbeato — COMMENTED** [review]
I have taken a look at https://launchpad.net/~canonical-foundations/+archive/ubuntu/ubuntu-image/+packages?field.name_filter=&field.status_filter=published&field.series_filter=focal and apparently we would also need the `secureboot-db` package in the ucdev ppa too. Should we just copy it? I have noticed that version 1.6~20.04.1 has been in focal-proposed for a long time, not sure why that happened.

**Comment by vorlonofportland** [comment]
> and apparently we would also need the `secureboot-db` package in the ucdev ppa too. Should we just copy it? I have noticed that version 1.6~20.04.1 has been in focal-proposed for a long time, not sure why that happened.

The secureboot-db package update revokes old versions of shim and as a result may cause systems (particularly dual-boot systems) to be unbootable after application of the firmware update.  It was delayed because for a time, Fedora was not ready to boot with the new revocation list.  Since then there have been significant additional revocations, so this SRU will eventually be superseded.

**Comment by valentindavid** [comment]
> I have taken a look at https://launchpad.net/~canonical-foundations/+archive/ubuntu/ubuntu-image/+packages?field.name_filter=&field.status_filter=published&field.series_filter=focal and apparently we would also need the secureboot-db package in the ucdev ppa too. Should we just copy it? I have noticed that version 1.6~20.04.1 has been in focal-proposed for a long time, not sure why that happened.

I have copied it to uc-dev before creating this PR.

**Comment by valentindavid** [comment]
Did not realize this was opened. Seems we did it in https://github.com/snapcore/core20/pull/157

I close it.

**Pull request closed without merging**
