### PR TITLE
Use release instead of daily image since it was removed

### PR DESCRIPTION
**Pull request by valentindavid**

### CODE REVIEW

**Review by alfonsosanchezbeato — APPROVED** [review]
LGTM, thanks

**Comment by valentindavid** [comment]
@alfonsosanchezbeato I added another commit to make the CI to pass. Is it still OK to merge?

**Review by xnox — APPROVED** [review]

**Review by xnox — CHANGES_REQUESTED** [review]
Hm, that's a bit odd though. We rely on up to date daily images as a starting point.

@vorlonofportland @sil2100 is that intentional that ubuntu-base focal dailies got stopped & removed from cdimage? Is that correct that core20 snaps now must use out of date / frozen in time base to build?

**Comment by vorlonofportland** [comment]
> Hm, that's a bit odd though. We rely on up to date daily images as a starting point.
> 
> @vorlonofportland @sil2100 is that intentional that ubuntu-base focal dailies got stopped & removed from cdimage? Is that correct that core20 snaps now must use out of date / frozen in time base to build?

No, this was an oversight when I pruned focal from the crontab post-20.04.6.  I'll add it back.

**Comment by xnox** [comment]
http://cdimage.ubuntu.com/ubuntu-base/focal/daily/ are back, thanks a lot.

**Pull request closed without merging**
