### PR TITLE
Add arches

### PR DESCRIPTION
**Pull request by xnox**

### CODE REVIEW

**Comment by mvo5** [comment]
Thanks for this PR. It looks great, but unfortunately CI seems to be not quite working.

**Comment by anonymouse64** [comment]
This may work better if it is rebased on master to get https://github.com/snapcore/core20/pull/74 incorporated here

**Comment by xnox** [comment]
> This may work better if it is rebased on master to get #74 incorporated here

I can try, but previously any "snaps:" stanzas would fail to install any snaps. Installing them twice in a row would make them work. But overall it seemed impossible to use snaps on arm64 "just like on amd64". But hopefully enough time has passed to have all of that fixed.

**Comment by xnox** [comment]
doesn't work, whatever.

**Pull request closed without merging**
